language: python

services:
  - elasticsearch

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

before_install:
  - sudo service elasticsearch start

install:
  - pip install .

script: python setup.py test
